name = "chronos-web"
compatibility_date = "2024-11-18"
# Required for Next.js on Pages
compatibility_flags = [ "nodejs_compat" ]

# OpenNext build output directory
pages_build_output_dir = ".open-next"

[vars]
# Public environment variables
NEXT_PUBLIC_SITE_URL = "https://automatonicai.com"
NEXT_PUBLIC_DIRECTUS_URL = "https://admin.automatonicai.com"

[[hyperdrive]]
binding = "DB"
id = "cbdc3f3e22f3454580f0d1ab56c9a1ea"

[[r2_buckets]]
binding = "MEDIA"
bucket_name = "chronos-media"
